# if EXPLOSION_ODDS is 200, mining a coal ore has a 1/200 chance of exploding
# COAL_DAMAGE = how many half hearts of damage
# FIRE_TICKER = how many ticks player will burn for. 200 = 2 seconds
# BOOM_RADIUS = radius of ore explosion
# DAMAGE_MESSAGE = message received on explosion
EXPLOSION_ODDS: 200
COAL_DAMAGE: 1
FIRE_TICKER: 200
BOOM_RADIUS: 2
DAMAGE_MESSAGE: '*cough*'
